version: '3.8'

services:
  test-db:
    container_name: postgresTest
    image: postgres:latest
    restart: on-failure
    env_file:
      - .test.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d Blog -U postgres" ]
      interval: 5s
      timeout: 20s
      retries: 100

  app-test:
    container_name: fastapi-app-test

    build:
      context: .
      dockerfile: Dockerfile
      target: test
    env_file:
      - .test.env
    depends_on:
      test-db:
        condition: service_healthy