version: '3.8'

services:
  test-db:
    container_name: postgresProd
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d Blog -U postgres" ]
      interval: 5s
      timeout: 20s
      retries: 100

  app-test:
    container_name: fastapi-app-prod
    ports:
      - "8000:8000"
    expose:
      - 8000
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env
    depends_on:
      test-db:
        condition: service_healthy