"""empty message

Revision ID: 0b30ea738bc1
Revises: 13f744c06e86
Create Date: 2023-09-07 02:15:36.250048

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0b30ea738bc1"
down_revision = "13f744c06e86"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("verse_table", "lyrics", existing_type=sa.VARCHAR(length=500), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("verse_table", "lyrics", existing_type=sa.VARCHAR(length=500), nullable=True)
    # ### end Alembic commands ###
