"""empty message

Revision ID: 0e9df697a904
Revises:
Create Date: 2023-11-16 00:00:46.725941

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e9df697a904"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tab_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=125), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["song_id"], ["song_table.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tab_table")
    # ### end Alembic commands ###
