"""empty message

Revision ID: 0ffafaf6f5fe
Revises: 9068885dff75
Create Date: 2023-08-06 15:16:08.525339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffafaf6f5fe'
down_revision = '9068885dff75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
