"""empty message

Revision ID: 275015374917
Revises: 6d07a080234b
Create Date: 2023-07-31 18:05:30.677770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275015374917'
down_revision = '6d07a080234b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
