"""empty message

Revision ID: 2951cbd1a014
Revises: 94c4ba814314
Create Date: 2023-07-31 17:12:43.615075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2951cbd1a014'
down_revision = '94c4ba814314'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
