"""empty message

Revision ID: 373c680a6588
Revises: 
Create Date: 2023-11-04 22:57:40.264620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373c680a6588'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hit_counter_blacklist_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['song_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'song_id', name='hit_counter_ff')
    )
    op.add_column('song_table', sa.Column('hits_count', sa.Integer(), nullable=True))
    op.add_column('user_table', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'username')
    op.drop_column('song_table', 'hits_count')
    op.drop_table('hit_counter_blacklist_table')
    # ### end Alembic commands ###
