"""empty message

Revision ID: 482bb02f48ad
Revises: 9eb302a3a03b
Create Date: 2023-08-06 16:15:45.277319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482bb02f48ad'
down_revision = '9eb302a3a03b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
