"""empty message

Revision ID: 4a7a16f00177
Revises: 8d1b9d4dc30a
Create Date: 2023-08-06 18:58:37.558413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7a16f00177'
down_revision = '8d1b9d4dc30a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
