"""change verse len

Revision ID: 5ae51a754011
Revises: 6907fedd1656
Create Date: 2023-08-30 14:50:59.743674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae51a754011'
down_revision = '6907fedd1656'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
