"""change verse len

Revision ID: 6907fedd1656
Revises: 777c2fd6756d
Create Date: 2023-08-30 14:50:00.683575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6907fedd1656'
down_revision = '777c2fd6756d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
