"""empty message

Revision ID: 6cf330dc7b49
Revises: 3b3c5c2a84a8
Create Date: 2023-08-03 22:27:42.268244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf330dc7b49'
down_revision = '3b3c5c2a84a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song_table', 'lyrics',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song_table', 'lyrics',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
