"""empty message

Revision ID: 7350b0efd751
Revises: 8d3a5d224eae
Create Date: 2023-08-08 01:13:39.609868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7350b0efd751'
down_revision = '8d3a5d224eae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verse_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=125), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('lyrics', sa.String(length=255), nullable=True),
    sa.Column('chords', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('song_table', 'lyrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_table', sa.Column('lyrics', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('verse_table')
    # ### end Alembic commands ###
