"""change verse len

Revision ID: 777c2fd6756d
Revises: 8f41038043fb
Create Date: 2023-08-30 14:48:28.683124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777c2fd6756d'
down_revision = '8f41038043fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
