"""empty message

Revision ID: 78dfbc8194bc
Revises: 0ffafaf6f5fe
Create Date: 2023-08-06 15:17:11.344546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78dfbc8194bc'
down_revision = '0ffafaf6f5fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('song_table_band_id_fkey', 'song_table', type_='foreignkey')
    op.drop_column('song_table', 'band_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_table', sa.Column('band_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('song_table_band_id_fkey', 'song_table', 'band_table', ['band_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
