"""empty message

Revision ID: 8d1b9d4dc30a
Revises: 482bb02f48ad
Create Date: 2023-08-06 16:24:06.909649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1b9d4dc30a'
down_revision = '482bb02f48ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
