"""empty message

Revision ID: 8e867b1151bf
Revises: ca0df3ed92f9
Create Date: 2023-11-23 02:53:36.312541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e867b1151bf'
down_revision = 'ca0df3ed92f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
