"""empty message

Revision ID: 8f8ce78a6b44
Revises: a8b621a538f7
Create Date: 2023-08-06 20:21:02.980307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8ce78a6b44'
down_revision = 'a8b621a538f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
