"""empty message

Revision ID: 94c4ba814314
Revises: 418cc41aa2fb
Create Date: 2023-07-31 17:06:40.552712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c4ba814314'
down_revision = '418cc41aa2fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
