"""empty message

Revision ID: a8b621a538f7
Revises: acafd1dd2d83
Create Date: 2023-08-06 19:18:31.434689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b621a538f7'
down_revision = 'acafd1dd2d83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
