"""empty message

Revision ID: a97522057cd4
Revises: d682232f0d8e
Create Date: 2024-01-29 16:58:27.778071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97522057cd4'
down_revision = 'd682232f0d8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_table', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song_table', 'description')
    # ### end Alembic commands ###
