"""empty message

Revision ID: acafd1dd2d83
Revises: 4a7a16f00177
Create Date: 2023-08-06 19:17:26.776223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acafd1dd2d83'
down_revision = '4a7a16f00177'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
