"""empty message

Revision ID: b2a34d5c2eb9
Revises: e644dbf4a93b
Create Date: 2023-07-30 21:20:25.221610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a34d5c2eb9'
down_revision = 'e644dbf4a93b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
