"""empty message

Revision ID: b5289accfec2
Revises: 6cf330dc7b49
Create Date: 2023-08-06 15:06:32.076917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5289accfec2'
down_revision = '6cf330dc7b49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
