"""empty message

Revision ID: ca0df3ed92f9
Revises: 0e9df697a904
Create Date: 2023-11-23 02:48:46.306268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0df3ed92f9'
down_revision = '0e9df697a904'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_table', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song_table', 'description')
    # ### end Alembic commands ###
