"""empty message

Revision ID: ccc5c802dddd
Revises: 
Create Date: 2023-07-30 00:16:54.421691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc5c802dddd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musician_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=125), nullable=False),
    sa.Column('last_name', sa.String(length=125), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=125), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table')
    op.drop_table('musician_table')
    # ### end Alembic commands ###
