"""empty message

Revision ID: d95f2d275a98
Revises: 2951cbd1a014
Create Date: 2023-07-31 17:59:32.211562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95f2d275a98'
down_revision = '2951cbd1a014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
