"""empty message

Revision ID: f6e9e9166c54
Revises: 8b9c39fe1ae9
Create Date: 2023-09-07 15:15:27.501469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e9e9166c54'
down_revision = '8b9c39fe1ae9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verse_table', 'lyrics',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('verse_table', 'chords',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verse_table', 'chords',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('verse_table', 'lyrics',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
