"""empty message

Revision ID: fde8d897f4c6
Revises: 8e867b1151bf
Create Date: 2023-11-24 00:22:02.960317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde8d897f4c6'
down_revision = '8e867b1151bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
