"""change verse len

Revision ID: 20310770be33
Revises: 5ae51a754011
Create Date: 2023-08-31 19:03:55.940606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20310770be33'
down_revision = '5ae51a754011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_table_email_key', 'user_table', type_='unique')
    op.drop_constraint('user_table_username_key', 'user_table', type_='unique')
    op.create_unique_constraint(None, 'user_table', ['telegram_id'])
    op.drop_column('user_table', 'email')
    op.drop_column('user_table', 'username')
    op.drop_column('user_table', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('user_table', sa.Column('username', sa.VARCHAR(length=125), autoincrement=False, nullable=False))
    op.add_column('user_table', sa.Column('email', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_table', type_='unique')
    op.create_unique_constraint('user_table_username_key', 'user_table', ['username'])
    op.create_unique_constraint('user_table_email_key', 'user_table', ['email'])
    op.drop_column('user_table', 'telegram_id')
    # ### end Alembic commands ###
