"""empty message

Revision ID: 3b3c5c2a84a8
Revises: 74a83e6879e0
Create Date: 2023-07-31 18:08:41.435157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3c5c2a84a8'
down_revision = '74a83e6879e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('musician_band_ff', 'musician_band_table', ['band_id', 'musician_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('musician_band_ff', 'musician_band_table', type_='unique')
    # ### end Alembic commands ###
