"""empty message

Revision ID: 418cc41aa2fb
Revises: 9ad558d61c37
Create Date: 2023-07-31 16:34:58.593596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418cc41aa2fb'
down_revision = '9ad558d61c37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
