"""empty message

Revision ID: 6ad7f3a6669d
Revises: 8f8ce78a6b44
Create Date: 2023-08-06 20:25:02.456575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad7f3a6669d'
down_revision = '8f8ce78a6b44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
