"""empty message

Revision ID: 6d07a080234b
Revises: d95f2d275a98
Create Date: 2023-07-31 18:04:02.060024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d07a080234b'
down_revision = 'd95f2d275a98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
