"""empty message

Revision ID: 8a37fcc7a1f0
Revises: da2cf0fe0626
Create Date: 2023-07-30 23:38:36.805632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a37fcc7a1f0'
down_revision = 'da2cf0fe0626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
