"""empty message

Revision ID: 9ad558d61c37
Revises: 8a37fcc7a1f0
Create Date: 2023-07-31 15:26:03.108920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad558d61c37'
down_revision = '8a37fcc7a1f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
