"""empty message

Revision ID: 9eb302a3a03b
Revises: 78dfbc8194bc
Create Date: 2023-08-06 15:21:37.436838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb302a3a03b'
down_revision = '78dfbc8194bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
