"""empty message

Revision ID: e81ab9bc4987
Revises: b2a34d5c2eb9
Create Date: 2023-07-30 21:28:22.311923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81ab9bc4987'
down_revision = 'b2a34d5c2eb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
