from .base_chords import BASE_TABLATURE
from .chords_7 import SEPT_CHORDS_TABLATURE
from .sus2_chords import SUS2_CHORDS_TABLATURE

CHORDS_TABLATURE = BASE_TABLATURE | SEPT_CHORDS_TABLATURE | SUS2_CHORDS_TABLATURE
